# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

env:
  - GITHUB_TOKEN
  - HOMEBREW_TAP_GITHUB_TOKEN
  - COSIGN_EXPERIMENTAL=true

before:
  hooks:
    - go mod download
    - go mod verify

builds:
  - binary: inspect-certificate
    env:
      - CGO_ENABLED=0
    flags:
      - "-trimpath"
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "6"
      - "7"
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goarch: arm
        goos: windows
      - goarch: arm64
        goos: windows
    ldflags:
      - "-s"
      - "-w"
      - "-extldflags '-static'"
      - "-X main.version={{.Version}}"
      - "-X main.commit={{.Commit}}"
      - "-X main.date={{.Date}}"
      - "-X main.builtBy=goreleaser"
    main: .

archives:
  - format_overrides:
      - formats:
          - zip
        goos: windows
    formats:
      - tar.gz
    id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- tolower .Os }}_
      {{- if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - merge conflict
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - order: 0
      regexp: ^.*?feat(\([[:word:]]+\))??!?:.+$
      title: Features
    - order: 1
      regexp: ^.*?fix(\([[:word:]]+\))??!?:.+$
      title: Bug fixes
    - order: 2
      regexp: ^.*?perf(\([[:word:]]+\))??!?:.+$
      title: Performance improvements
    - order: 999
      title: Others
  sort: asc
  use: github

dist: .goreleaser-dist

release:
  draft: false
  prerelease: auto
  header: |
    ## What's Changed

    This release includes the following changes:
  footer: |
    ## Docker Images

    ```bash
    docker pull ghcr.io/meysam81/{{ .ProjectName }}:{{ .Version }}
    ```

    **Full Changelog**: https://github.com/meysam81/{{ .ProjectName }}/compare/{{ .PreviousTag }}...{{ .Tag }}

binary_signs:
  - args:
      - sign-blob
      - "--output-signature=${signature}"
      - "--output-certificate=${certificate}"
      - ${artifact}
      - "--yes"
    certificate: ${artifact}_{{- tolower .Os }}_{{- if eq .Arch "386" }}i386{{- else }}{{ .Arch }}{{ end }}{{- if .Arm }}v{{ .Arm }}{{ end }}.pem
    cmd: cosign
    output: false
    signature: ${artifact}_{{- tolower .Os }}_{{- if eq .Arch "386" }}i386{{- else }}{{ .Arch }}{{ end }}{{- if .Arm }}v{{ .Arm }}{{ end }}.sig

dockers_v2:
  - images:
      - meysam81/{{ .ProjectName }}
      - ghcr.io/meysam81/{{ .ProjectName }}
    tags:
      - "{{ if not .IsSnapshot }}v{{ .Version }}{{ end }}"
      - "{{ if not .IsSnapshot }}v{{ .Major }}{{ end }}"
      - "{{ if not .IsSnapshot }}v{{ .Major }}.{{ .Minor }}{{ end }}"
      - "{{ if not .IsSnapshot }}v{{ .Major }}.{{ .Minor }}.{{ .Patch }}{{ end }}"
      - "{{ .FullCommit }}"
      - "{{ if .IsNightly }}latest{{ end }}"
    extra_files:
      - ./
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.description": "Get detailed information about SSL/TLS certificates from the command line."
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
      "org.opencontainers.image.version": "{{.Version}}"
      # "io.modelcontextprotocol.server.name": "io.github.meysam81/inspect-certificate"
    platforms:
      - linux/amd64
      - linux/arm64
    sbom: "{{ not .Env.DISABLE_SBOM }}"
    build_args:
      VERSION: "{{.Version}}"
      COMMIT: "{{.FullCommit}}"
      DATE: "{{.Date}}"
      BUILT_BY: goreleaser

docker_signs:
  - id: default
    args:
      - "sign"
      - "--yes"
      - "${artifact}"
    cmd: cosign
    output: true

docker_digest:
  name_template: "digest.txt"
  disable: "{{ .Env.NO_DIGEST }}"

# mcp:
#   name: io.github.meysam81/inspect-certificate
#   title: Inspect-CERTIFICATE MCP Server
#   description: "Lightweight DMARC parser: auto-fetch email reports, visualize compliance in a single all-in-one app"
#   homepage: https://github.com/meysam81/inspect-certificate
#   auth:
#     type: github-oidc
#   repository:
#     url: "https://github.com/meysam81/inspect-certificate.git"
#     source: github
#     id: "1089959979"
#   packages:
#     - registry_type: oci
#       identifier: "ghcr.io/meysam81/inspect-certificate:{{ .Version }}"
#       transport:
#         type: streamable-http
#   disable: false

report_sizes: true

milestones:
  - close: true
    fail_on_error: false
    name_template: "{{ .Tag }}"

announce:
  skip: "{{gt .Patch 0}}"

checksum:
  algorithm: sha256
  name_template: checksums.txt

homebrew_casks:
  - commit_msg_template: Brew formula update for {{ .ProjectName }} version {{ .Tag }}
    description: Get detailed information about SSL/TLS certificates from the command line.
    homepage: https://github.com/meysam81/inspect-certificate
    license: Apache-2.0
    name: inspect-certificate
    repository:
      name: homebrew-tap
      owner: meysam81
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/inspect-certificate"]
          end
